baseURL = "https://llmo.org"
title = "LLMO"
defaultContentLanguage = "en"

ignoreFiles = ['^README\.md$', '^CONTRIBUTING\.md$', '^SECURITY\.md$', '^BACKLOG\.md$', '^infrastructure/', '^scripts/', '^design/', '^\.github/']
